//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crypto.Web.Shared.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crypto.Web.Shared.ResourceFiles.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        public static string Conversion_button {
            get {
                return ResourceManager.GetString("Conversion_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose currency 1.
        /// </summary>
        public static string Conversion_Choose1 {
            get {
                return ResourceManager.GetString("Conversion_Choose1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose currency 2.
        /// </summary>
        public static string Conversion_Choose2 {
            get {
                return ResourceManager.GetString("Conversion_Choose2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter quantity.
        /// </summary>
        public static string Conversion_input {
            get {
                return ResourceManager.GetString("Conversion_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cryptocurrencies Conversion.
        /// </summary>
        public static string Conversion_title {
            get {
                return ResourceManager.GetString("Conversion_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All crypto currencies.
        /// </summary>
        public static string index_search_string {
            get {
                return ResourceManager.GetString("index_search_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter search name.
        /// </summary>
        public static string index_title {
            get {
                return ResourceManager.GetString("index_title", resourceCulture);
            }
        }
    }
}
